// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewyksmxiqhmplqjpbmpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3eWtzbXhpcWhtcGxxanBibXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxOTU0MDEsImV4cCI6MjA2Mjc3MTQwMX0.RmFCwa_X44GJEmIVqGuHBu9_GHZc51rjonb1QwXT3DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);